### ISSUE TITLE
Fix AssemblyResolveEvent to only redirect for certain assemblies

### ISSUE THREAD

**Issue by yurikus** [justemutarkov/Launcher#3]
I have a hunch that people are having trouble with the launcher because (in the new one, without published sources) assembly resolve event blindly redirects to `.._Data/Managed` dir and this fails for some people, thus hiding real other issues. IMHO, redirect needs to happen only for json and zlib dlls.

Screenshot from Russian #помощь:

![image](https://user-images.githubusercontent.com/11010776/73598372-25370980-44fd-11ea-8d8d-b6a6bfe14b2f.png)

**Comment by InNoHurryToCode** [comment]
This means that they didn't put the launcher inside of the right folder.
